// Photogrammetry material scans (ambientCG, CC0 1.0).
//
// These replace the procedural layers in the material atlas in place: same
// array, same layer indices, same shader. A scan simply overwrites the bytes a
// generator would have produced, so nothing downstream has to know the
// difference.
//
// Channel layout matches the procedural bake exactly:
//   ALBEDO  rgb = base colour (sRGB), a = ambient occlusion
//   SURF    rg  = tangent-space normal xy, b = roughness, a = metalness

import { MAT } from './textures.js';

const DIR = 'assets/materials/';

/**
 * `metres` is the real-world size of one tile, used to derive uvScale so
 * textures sit at physical scale instead of an arbitrary one. Values marked
 * (api) came from ambientCG's dimension data; the rest are authored from what
 * the material obviously is.
 *
 * `ao` and `metalMap` say which optional maps the set actually ships, so we
 * never fire a request for one that is not there.
 *
 * `metal` overrides the scan's own metalness map. Several of these scans are
 * bare metal but stand in for something painted — a shipping container is
 * steel underneath and a dielectric on the surface — and a metalness of 1
 * throws away the diffuse term, so the paint tint would do nothing but colour
 * the reflection. Where a slot states its metalness, the map is ignored.
 */
export const SCANS = {
  [MAT.SAND]: { asset: 'Ground093C', metres: 2.0, ao: 1 },
  [MAT.CONCRETE]: { asset: 'Concrete031', metres: 2.0, ao: 1 },
  [MAT.CONTAINER]: { asset: 'CorrugatedSteel005', metres: 2.4, ao: 1, metal: 0 },
  [MAT.CORRUGATED]: { asset: 'CorrugatedSteel005', metres: 1.4, ao: 1, metal: 0 },
  [MAT.WOOD]: { asset: 'Wood095', metres: 1.5 },
  [MAT.GUNMETAL]: { asset: 'Metal038', metres: 0.9, metalMap: 1 },
  [MAT.POLYMER]: { asset: 'Plastic011', metres: 0.5 },
  [MAT.SANDBAG]: { asset: 'Fabric028', metres: 0.7 },
  [MAT.RUSTBARREL]: { asset: 'Metal041B', metres: 1.0, metal: 90 },
  [MAT.ASPHALT]: { asset: 'Asphalt022', metres: 1.85, ao: 1 },           // (api) 185cm
  [MAT.FATIGUES]: { asset: 'Fabric066', metres: 0.40, ao: 1 },           // (api) 40cm
  [MAT.BRICK]: { asset: 'Bricks104', metres: 1.5, ao: 1 },
  [MAT.MUDBRICK]: { asset: 'Bricks091', metres: 2.2, ao: 1 },
};

/** uvScale for a slot, so one tile covers its real-world size. */
export function scanUV(layer) {
  const s = SCANS[layer];
  return s ? 1 / s.metres : null;
}

function loadImage(url) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img);
    // A missing map is normal — not every scan ships AO or metalness.
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

/**
 * Decodes the scans and writes them over the given atlas layers.
 * Failures are per-map and non-fatal: whatever cannot be loaded simply keeps
 * the procedurally generated bytes underneath.
 */
export async function applyScans(albedo, surf, N, onProgress) {
  const canvas = document.createElement('canvas');
  canvas.width = N; canvas.height = N;
  const ctx = canvas.getContext('2d', { willReadFrequently: true });
  if (!ctx) return 0;

  const cache = new Map();
  const read = async (url) => {
    if (cache.has(url)) return cache.get(url);
    const img = await loadImage(url);
    if (!img) { cache.set(url, null); return null; }
    ctx.clearRect(0, 0, N, N);
    ctx.drawImage(img, 0, 0, N, N);
    const data = ctx.getImageData(0, 0, N, N).data;
    cache.set(url, data);
    return data;
  };

  const layers = Object.keys(SCANS).map(Number);
  let done = 0, applied = 0;

  for (const layer of layers) {
    const def = SCANS[layer];
    const base = `${DIR}${def.asset}_`;
    const [color, normal, rough, ao, metal] = await Promise.all([
      read(`${base}Color.jpg`),
      read(`${base}NormalGL.jpg`),
      read(`${base}Roughness.jpg`),
      def.ao ? read(`${base}AmbientOcclusion.jpg`) : null,
      def.metalMap ? read(`${base}Metalness.jpg`) : null,
    ]);

    if (color && normal && rough) {
      const off = layer * N * N * 4;
      for (let i = 0; i < N * N; i++) {
        const o = off + i * 4, p = i * 4;
        // Colour JPEGs are already sRGB and the array is SRGB8_ALPHA8, so the
        // bytes copy straight across with no conversion.
        albedo[o] = color[p];
        albedo[o + 1] = color[p + 1];
        albedo[o + 2] = color[p + 2];
        albedo[o + 3] = ao ? ao[p] : 255;

        surf[o] = normal[p];
        surf[o + 1] = normal[p + 1];
        surf[o + 2] = rough[p];
        surf[o + 3] = def.metal === undefined ? (metal ? metal[p] : 0) : def.metal;
      }
      applied++;
    } else {
      console.warn(`[scans] ${def.asset}: incomplete, keeping procedural layer`);
    }
    done++;
    if (onProgress) onProgress(done / layers.length);
  }
  return applied;
}
